### PR TITLE
(WIP) Web Visualizer 

### PR DESCRIPTION
**Pull request by SeanAvery**
This is a base case for getting a graph to render on a webapp from simulation runs.

To Run:

- `npm i`
- `npm run start-server`
- `npm run wds`
- `localhost:8080`

1. Plot Tool JSON dump
- Simple iterating through nodes and edges and dumping json

2. Websocket
- accepts form submissions and parses into arguments for python shell hit
- relays json emissions to web app

3. React/Redux/vis.js App
- middleware hooks into websocket and listens for msgs
- accepts `graph_data` objects each simulation interval and updates graph

### CODE REVIEW

**Comment by djrtwo** [comment]
Just got it running! Great start :)
Just a quick note, I had to manually install `babel-cli` to get it running. Was getting `babel-node: command not found` before I did that.

I love the self-organizing, almost creature-like graph that forms, but I am also interested inducing structure. Does this tool allow you to manage the visual structure more explicitly?

**Comment by SeanAvery** [comment]
@djrtwo  `babel-cli` issue noted, I will add it to the local dependencies.

Yes, `vis.js` has a `layout` api which lets you position things in the x-y plane. I am experimenting with it now and it seems to be sufficiently expressive :) 

I am also currently adding in edge details like dash/solid and coloring.

It is looking like different network topologies (full, rand, round-robin, ...) will look best with unique physics and layout properties.

**Comment by naterush** [comment]
@SeanAvery This is awesome! Can you point this PR at `develop` rather than `master`?

**Comment by naterush** [comment]
Also - when running this the viewgraphs pop-up as well. Not sure if this is intended behavior, but I think it would be better if these weren't displayed while the d3- visualizations are going on.

**Comment by SeanAvery** [comment]
@naterush Yes, will change pr base. Agreed :) I was keeping viewgraphs mostly for comparison tests, but will work on a more clean solution to separate out the viewgraph rendering when the web visualization is intended.

## update ##
- I now have all of the edge styles incorporated (dashes, coloring, ...)
- Goal for today is to start to incorporate the node details. (weight sizing and finality coloring) 
- Also experimenting with more controlled graph layouts for `rand` and `rrobin` networks

**Comment by SeanAvery** [comment]
## Update ##

The node.js server + python shell + websocket interface is working well but the visualization needs an overhaul. 

The current visualization uses http://visjs.org/. The physics engine lacks coulomb's law functionality making it hard to space out nodes in a given container. 

I am working on rebuilding it out just using the d3-force library. I would like both message passes and clique detection to be shown in the same visualization (via a toggling mechanism). I am currently thinking the best way to achieve this is in a 3-dimensional force graph [example here](https://bl.ocks.org/vasturiano/f59675656258d3f490e9faa40828c0e7)

I have also been toying around with 3d graphs just using plotly + matplotlib-- but again I am having a problem with a lack of a physics engine. I do think scalability is a concern in a web app environment as I am already noticed significant performance hits when pushing large json payloads. There are other more performant tools such as [cytoscape](http://www.cytoscape.org/), built for biology research, that we can look into as well.

**Pull request closed without merging**
