### PR TITLE
Chore/int cleanup

### PR DESCRIPTION
**Pull request by djrtwo**
- binary reuses code from integer
- rename BinaryPlotTool to IntegerPlotTool
- simplify Integer estimator
- move protocols into `casper/protocols`
- add a few tests for binary case in integer estimator

### CODE REVIEW

**Comment by djrtwo** [comment]
whoops, my last commit made this tough to review.

**Comment by naterush** [comment]
@djrtwo what's the benefit of defining this as a property? Not that I have an issue with it, just can't think of a situation where it would be useful. 

This looks dope, though! Really nice abstraction :)

**Comment by naterush** [comment]
Can you add tests for the different min/max if possible? I guess it's just a simple override but would be good to test.

**Comment by djrtwo** [comment]
Will add tests!

The @property works well for binary because it makes it clear not to override. It shouldn't be a @property for Integer and should be an optional param. Will alter and add tests

**Comment by djrtwo** [comment]
updated. ready for final review

**Comment by djrtwo** [comment]
ping

**Pull request merged**
